version: "3.9"
services:
  worker:
    build: .
    environment:
      STRING_SESSION: $STRING_SESSION
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      BOT_TOKEN: $BOT_TOKEN # Not mandatory
      DATABASE_URL: $DATABASE_URL  # defaults to None
      ENV: $ENV
      TG_BOT_USERNAME: $TG_BOT_USERNAME
      TG_BOT_TOKEN: $TG_BOT_TOKEN
      TZ: $TZ
      ALIVE_NAME: $ALIVE_NAME
